[package]
name = "bevy_kira_audio"
version = "0.11.0"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://docs.rs/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"
rust-version = "1.56.1"

[features]
default = ["ogg"]
mp3 = ["kira/mp3"]
ogg = ["kira/ogg"]
flac = ["kira/flac"]
settings_loader = ["ron", "serde"]
wav = ["kira/wav"]

[dependencies]
# bevy
bevy = { version = "0.11", default-features = false, features = ["bevy_asset", "bevy_render", ] }
# other
anyhow = "1.0"
kira = { version = "0.5.2", default-features = false }
parking_lot = "0.11.0"
ron = { version = "0.6.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
bevy = { version = "0.10", features = ["bevy_asset", "bevy_gltf", "bevy_winit", "bevy_render"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["ogg"]

[[example]]
name = "custom_channel"
path = "examples/custom_channel.rs"
required-features = ["ogg"]

[[example]]
name = "multiple_channels"
path = "examples/multiple_channels.rs"
required-features = ["ogg"]

[[example]]
name = "semantic_duration"
path = "examples/semantic_duration.rs"
required-features = ["ogg", "settings_loader"]

[[example]]
name = "status"
path = "examples/status.rs"
required-features = ["ogg"]

[[example]]
name = "stream"
path = "examples/stream.rs"
